[workspace]
members = [
  "bmap",
  "bmap-rs",
]

# Most of the actual work is CPU-heavy, in particular the rust sha2
# implementation so use full optimisations otherwise everything will run quite
# slow
[profile.dev]
opt-level = 3
