[package]
name = "bmap-rs"
version = "0.1.0"
authors = ["Sjoerd Simons <sjoerd@collabora.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bmap = { path = "../bmap" }
anyhow = "1"
nix = "0.25"
flate2 = "1"
clap = { version = "4.0.18", features = ["derive"] }
